### PR TITLE
Remove shebang

### PR DESCRIPTION
**Pull request by christianbundy**
This allows the module to be used in the browser.

### CODE REVIEW

**Comment by dominictarr** [comment]
this breaks it as a command, can you make a bin.js file that has the `#!`

**Comment by christianbundy** [comment]
Done, I've moved the shebang and the `if(!module.parent)` to `bin.js`, fixed the permissions, and updated `package.json` with the new path. Please let me know if there's anything else, thanks for the quick review!

**Comment by cryptix** [comment]
@dominictarr can we merge this please?

**Comment by dominictarr** [comment]
merged into 1.4.3

**Comment by christianbundy** [comment]
Thanks!

**Pull request merged**
